# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: admin.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'admin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61\x64min.proto\"\x16\n\x05Login\x12\r\n\x05login\x18\x01 \x02(\t\"\x18\n\x06Status\x12\x0e\n\x06status\x18\x01 \x02(\x08\x32-\n\x05\x41\x64min\x12$\n\x0f\x43heckValidLogin\x12\x06.Login\x1a\x07.Status\"\x00')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'admin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGIN']._serialized_start=15
  _globals['_LOGIN']._serialized_end=37
  _globals['_STATUS']._serialized_start=39
  _globals['_STATUS']._serialized_end=63
  _globals['_ADMIN']._serialized_start=65
  _globals['_ADMIN']._serialized_end=110
# @@protoc_insertion_point(module_scope)
